# Sonar Fusion Configuration

# Field dimensions (meters)
field:
  width: 3.0
  height: 3.0
  center:
    x: 0.0  # World coordinate system origin
    y: 0.0

# Sensor configuration (World coordinate system: origin at field center)
sensors:
  - id: 1
    name: "Sensor_1" 
    position:
      x: -1.5  # Southwest corner
      y: -1.5
      z: 0.5   # height above ground
    servo:
      pan_range: [-90, 90]     # degrees relative to home direction
      pan_speed: 180.0         # degrees per second
    max_range: 2.5  # meters
    
  - id: 2
    name: "Sensor_2"
    position:
      x: 1.5   # Southeast corner
      y: -1.5
      z: 0.5
    servo:
      pan_range: [-90, 90]
      pan_speed: 180.0
    max_range: 2.5
    
  - id: 3
    name: "Sensor_3"
    position:
      x: 1.5   # Northeast corner  
      y: 1.5
      z: 0.5
    servo:
      pan_range: [-90, 90]
      pan_speed: 180.0
    max_range: 2.5
    
  - id: 4
    name: "Sensor_4"
    position:
      x: -1.5  # Northwest corner
      y: 1.5
      z: 0.5
    servo:
      pan_range: [-90, 90]
      pan_speed: 180.0
    max_range: 2.5

# Tracking parameters
tracking:
  # Kalman filter parameters
  kalman:
    process_noise: 0.1
    measurement_noise_distance: 0.02  # 2cm standard deviation
    measurement_noise_pan: 2.0        # 2 degrees standard deviation
    initial_covariance: 1.0
    
  # Association parameters
  association:
    max_distance: 0.5  # meters
    min_confidence: 0.3
    
  # Track management
  track_management:
    init_threshold: 2      # measurements needed to create track
    delete_threshold: 5    # missed updates before deletion
    max_tracks: 10

# Communication settings
communication:
  serial:
    baudrate: 115200
    timeout: 0.1  # seconds
  message_rate: 80  # milliseconds between messages per sensor

# Visualization settings
visualization:
  update_rate: 30  # Hz
  trail_length: 50  # number of points in trail
  colors:
    sensors: "blue"
    measurements: "red"
    tracks: "green"
    ground_truth: "black"
  
# Simulation settings
simulation:
  scenario: "circle"  # Options: "all", "diagonal", "circle", "random", "diagonal_circle", "diagonal_random", "circle_random"
  num_targets: 1
  target_speed: 2.0  # m/s
  noise:
    distance_std: 0.02  # meters
    pan_std: 2.0        # degrees
  bounce: true  # bounce off walls
  servo_tracking: true  # simulate servo following targets